# Generated by Django 3.2.19 on 2023-12-29 07:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hours_logger', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='invoice',
            old_name='invoice',
            new_name='id',
        ),
        migrations.AlterField(
            model_name='shift',
            name='hours',
            field=models.FloatField(),
        ),
        migrations.AlterField(
            model_name='shift',
            name='price',
            field=models.FloatField(),
        ),
        migrations.AlterField(
            model_name='shift',
            name='total',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
