# Generated by Django 3.2.19 on 2024-01-01 06:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hours_logger', '0004_auto_20240101_0635'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='employee',
            name='groups',
        ),
        migrations.RemoveField(
            model_name='employee',
            name='is_superuser',
        ),
        migrations.RemoveField(
            model_name='employee',
            name='last_login',
        ),
        migrations.RemoveField(
            model_name='employee',
            name='password',
        ),
        migrations.RemoveField(
            model_name='employee',
            name='user_permissions',
        ),
        migrations.AlterField(
            model_name='employee',
            name='email',
            field=models.EmailField(max_length=254),
        ),
    ]
