# Generated by Django 3.2.19 on 2024-01-05 08:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hours_logger', '0008_remove_shift_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='shift',
            name='hours',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
