# Generated by Django 3.2.19 on 2024-01-05 08:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hours_logger', '0009_alter_shift_hours'),
    ]

    operations = [
        migrations.RenameField(
            model_name='shift',
            old_name='end',
            new_name='end_time',
        ),
        migrations.RenameField(
            model_name='shift',
            old_name='start',
            new_name='start_time',
        ),
        migrations.AlterField(
            model_name='employee',
            name='phoneNumber',
            field=models.CharField(max_length=15),
        ),
    ]
