# Generated by Django 3.2.19 on 2024-01-07 06:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('hours_logger', '0010_auto_20240105_0815'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='invoice',
            name='date',
        ),
    ]
