# Generated by Django 3.2.19 on 2024-01-07 06:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hours_logger', '0011_remove_invoice_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='pauselog',
            name='pauseDuration',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
