# Generated by Django 3.2.19 on 2024-01-07 06:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hours_logger', '0012_pauselog_pauseduration'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pauselog',
            name='pauseDuration',
            field=models.DurationField(blank=True, null=True),
        ),
    ]
