# Generated by Django 3.2.19 on 2024-01-07 08:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hours_logger', '0013_alter_pauselog_pauseduration'),
    ]

    operations = [
        migrations.RenameField(
            model_name='shift',
            old_name='start_time',
            new_name='start',
        ),
        migrations.AlterField(
            model_name='employee',
            name='phoneNumber',
            field=models.CharField(max_length=10),
        ),
    ]
