# Generated by Django 3.2.19 on 2024-01-07 08:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('hours_logger', '0014_auto_20240107_0828'),
    ]

    operations = [
        migrations.RenameField(
            model_name='shift',
            old_name='end_time',
            new_name='end',
        ),
    ]
