# Generated by Django 3.2.19 on 2024-01-07 08:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hours_logger', '0015_rename_end_time_shift_end'),
    ]

    operations = [
        migrations.AlterField(
            model_name='shift',
            name='end',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
