# Generated by Django 3.2.19 on 2024-01-07 08:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hours_logger', '0016_alter_shift_end'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employee',
            name='address',
            field=models.CharField(max_length=254),
        ),
    ]
