# Generated by Django 3.2.19 on 2024-01-24 02:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hours_logger', '0017_alter_employee_address'),
    ]

    operations = [
        migrations.AddField(
            model_name='employee',
            name='hourlyRate',
            field=models.FloatField(default=0.0),
        ),
    ]
